name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  test_351x:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run Tests
      run: |
        echo $(pwd)
        echo $(ls)
        docker pull nrel/openstudio:3.8.0
        docker run --name test --rm -d -t -v $(pwd):/work -w /work nrel/openstudio:3.8.0
        docker exec -t test pwd
        docker exec -t test ls
        docker exec -t test bundle update
        docker exec -t test bundle exec rake
        docker kill test
